#!/usr/bin/env python3.11
"""
arch_guard.py — детектирует и документирует архитектурные изменения.

При каждом изменении .py-файлов:
  1. AST-парсит граф зависимостей между модулями проекта
  2. Сравнивает с сохранённым снимком (.arch_graph.json)
  3. Если граф изменился — обновляет ARCH_SNAPSHOT.md (раздел ГРАФ ЗАВИСИМОСТЕЙ)
     и дописывает запись в лог архитектурных изменений
  (Пункт 4 «предупреждает, если новый .py не зарегистрирован в gen_blueprint.py»
   снят 2026-08-02: механизма в коде НЕ БЫЛО — ни одного обращения к
   gen_blueprint.MODULES здесь никогда не стояло, обещание жило только в этой
   строке. Сам MODULES снят вместе с §25. Периметр графа задаёт TRACKED ниже —
   и он рукописный: 92 записи против 318 .py в репо, 4 из них про
   несуществующие модули. Это известное ограничение, не покрытие.)

Запуск:
  python3.11 arch_guard.py               # проверить + обновить
  python3.11 arch_guard.py --dry-run     # показать граф, не писать
  python3.11 arch_guard.py --pre-commit  # режим хука (всегда exit 0)

Вызывается из: .git/hooks/pre-commit, run_checks.sh
"""

import argparse
import ast
import json
import sys
from datetime import datetime
from pathlib import Path

ROOT          = Path(__file__).parent
ARCH_SNAPSHOT = ROOT / "ARCH_SNAPSHOT.md"
GRAPH_CACHE   = ROOT / ".arch_graph.json"
LOG           = ROOT / "logs" / "arch_guard.log"

DRY_RUN    = "--dry-run"    in sys.argv
PRE_COMMIT = "--pre-commit" in sys.argv

_TEXT = {
    "ru": {
        "graph": "## ГРАФ ЗАВИСИМОСТЕЙ",
        "all_modules": "-- ВСЕ МОДУЛИ → health_db (единственная точка данных)",
        "no_imports": "-- health_db НЕ импортирует ничего внутреннего",
        "log": "## ЛОГ АРХИТЕКТУРНЫХ ИЗМЕНЕНИЙ",
        "new": "новый модуль `{mod}` (зависит от: {deps})",
        "deleted": "удалён модуль `{mod}`",
        "added": "`{mod}` + зависимость: {deps}",
        "removed": "`{mod}` − зависимость: {deps}",
        "more": " (+{count} изменений)"
    },
    "en": {
        "graph": "## DEPENDENCY GRAPH",
        "all_modules": "-- ALL MODULES → health_db (single data access point)",
        "no_imports": "-- health_db imports no internal modules",
        "log": "## ARCHITECTURE CHANGE LOG",
        "new": "new module `{mod}` (depends on: {deps})",
        "deleted": "removed module `{mod}`",
        "added": "`{mod}` + dependency: {deps}",
        "removed": "`{mod}` − dependency: {deps}",
        "more": " (+{count} changes)",
        "header": "<!-- Generated by arch_guard.py; descriptions are machine-translated from the Russian source. -->",
        "history": "History before {today} is in the Russian [ARCH_SNAPSHOT.md](ARCH_SNAPSHOT.md)."
    }
}

# ── Модули, которые считаются «проектными» ────────────────────────────────────
# (только они отслеживаются в графе; stdlib и pip-пакеты — игнорируются)

def _tracked_modules() -> set[str]:
    """Периметр графа ВЫЧИСЛЯЕТСЯ из дерева, а не описывается списком (CLAUDE.md §18).

    До 2026-08-03 здесь стоял рукописный набор из 92 имён. Замер того дня: живых
    .py в репозитории 318, четыре записи набора указывали на несуществующие модули,
    230 файлов были вне периметра. И это не косметика: TRACKED фильтрует РЁБРА —
    зависимость на модуль вне набора просто не попадала в граф, поэтому «Граф
    зависимостей модулей» показывал 151 узел, будучи подмножеством по построению.
    Механизм-напоминание при этом работал и накопил 2520 строк «не в TRACKED —
    добавь» в logs/run_checks.log, которые никто не читал (§13, banner-blindness).

    Теперь регистрировать нечего: периметр — то, что лежит в git. Корневые модули,
    как и раньше; пакеты (bot/, project_context/, jobs/) в граф по-прежнему не входят,
    и это названо здесь, а не подразумевается.
    """
    import subprocess as _sp
    try:
        out = _sp.run(["git", "ls-files", "*.py"], cwd=ROOT,
                      capture_output=True, text=True, check=True).stdout
    except (OSError, _sp.CalledProcessError):
        return {p.stem for p in ROOT.glob("*.py")}      # git недоступен — берём диск
    return {Path(f).stem for f in out.splitlines() if "/" not in f and f.endswith(".py")}


TRACKED = _tracked_modules()

# ── Парсинг импортов ──────────────────────────────────────────────────────────

def _log(msg: str):
    LOG.parent.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")  # time-inject: ok
    with open(LOG, "a") as f:
        f.write(f"{ts}  {msg}\n")


def parse_imports(path: Path) -> set[str]:
    """Возвращает множество проектных модулей, которые импортирует файл."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError:
        return set()

    deps: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                mod = alias.name.split(".")[0]
                if mod in TRACKED:
                    deps.add(mod)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                mod = node.module.split(".")[0]
                if mod in TRACKED:
                    deps.add(mod)
    return deps


def build_graph() -> dict[str, list[str]]:
    """Строит граф зависимостей: {module: [deps...]} для всех .py файлов проекта."""
    graph: dict[str, list[str]] = {}
    for path in sorted(ROOT.glob("*.py")):
        # Пропускаем патч-скрипты, кэш, сам себя
        if path.name.startswith("_") or path.name == "arch_guard.py":
            continue
        module = path.stem
        deps = parse_imports(path)
        deps.discard(module)          # убираем само-импорт
        if deps:
            graph[module] = sorted(deps)
    return graph


# ── Форматирование ────────────────────────────────────────────────────────────

def format_graph(graph: dict[str, list[str]], lang="ru") -> str:
    """Форматирует граф для ARCH_SNAPSHOT.md."""
    lines = []
    # Сначала модули с наибольшим числом зависимостей
    for mod in sorted(graph, key=lambda m: (-len(graph[m]), m)):
        deps = ", ".join(graph[mod])
        lines.append(f"{mod:<28} → {deps}")

    # Финальная строка
    lines.append("")
    lines.append(_TEXT[lang]["all_modules"])
    lines.append(_TEXT[lang]["no_imports"])
    return "\n".join(lines)

# ── Обновление ARCH_SNAPSHOT.md ───────────────────────────────────────────────

_GRAPH_START = "<!-- GEN:GRAPH:START -->"
_GRAPH_END   = "<!-- GEN:GRAPH:END -->"
_ARCH_LOG_START = "<!-- GEN:ARCH_LOG:START -->"
_ARCH_LOG_END   = "<!-- GEN:ARCH_LOG:END -->"


def _replace_section(content: str, start_marker: str,
                     end_marker: str, new_body: str) -> str:
    """Заменяет блок между маркерами. Если маркеров нет — добавляет в конец."""
    if start_marker in content and end_marker in content:
        import re
        pattern = re.escape(start_marker) + r".*?" + re.escape(end_marker)
        block = f"{start_marker}\n{new_body}\n{end_marker}"
        return re.sub(pattern, block, content, flags=re.DOTALL)
    # Маркеров нет — вставляем перед "## КЛЮЧЕВЫЕ ПАТТЕРНЫ"
    anchor = "## КЛЮЧЕВЫЕ ПАТТЕРНЫ"
    if anchor in content:
        idx = content.index(anchor)
        block = f"{start_marker}\n{new_body}\n{end_marker}\n\n"
        return content[:idx] + block + content[idx:]
    return content + f"\n\n{start_marker}\n{new_body}\n{end_marker}\n"


def update_arch_snapshot(graph: dict, diff_summary: str, today: str, lang="ru"):
    """Перезаписывает граф зависимостей и дописывает лог изменений."""
    text = _TEXT[lang]
    target = ARCH_SNAPSHOT if lang == "ru" else ARCH_SNAPSHOT.with_name("ARCH_SNAPSHOT.en.md")
    if not target.exists():
        _log(f"{target.name} не найден")
        return False

    content = target.read_text(encoding="utf-8")

    # 1. Обновляем граф
    graph_body = text["graph"] + "\n\n```\n" + format_graph(graph, lang) + "\n```"
    if lang == "en":
        graph_body = text["header"] + "\n" + graph_body
    content = _replace_section(content, _GRAPH_START, _GRAPH_END, graph_body)

    # 2. Дописываем лог архитектурных изменений
    new_entry = f"- `{today}` — {diff_summary}"
    if lang == "en":
        # Never read/copy the Russian history. Preserve only this English log.
        previous = ""
        if _ARCH_LOG_START in content and _ARCH_LOG_END in content:
            previous = content.split(_ARCH_LOG_START, 1)[1].split(_ARCH_LOG_END, 1)[0].strip()
        if not previous:
            previous = text["header"] + "\n" + text["history"].format(today=today)
        if diff_summary:
            header, _, history = previous.partition("\n")
            previous = header + "\n" + new_entry + "\n" + history
        content = _replace_section(content, _ARCH_LOG_START, _ARCH_LOG_END, previous)
    elif _ARCH_LOG_START in content and _ARCH_LOG_END in content:
        import re
        # Вставляем новую запись первой внутри блока
        pattern = re.escape(_ARCH_LOG_START) + r"\n"
        content = re.sub(pattern,
                         f"{_ARCH_LOG_START}\n{new_entry}\n",
                         content, count=1)
    else:
        log_block = (f"{_ARCH_LOG_START}\n{new_entry}\n{_ARCH_LOG_END}")
        content = content.rstrip() + f"\n\n{text['log']}\n\n{log_block}\n"

    if not DRY_RUN:
        target.write_text(content, encoding="utf-8")
        _log(f"{target.name} обновлён: {diff_summary}")
    else:
        print("--- DRY RUN ---")
        print(f"Граф обновлён. Лог: {new_entry}")
    return True

# ── Определение изменений ─────────────────────────────────────────────────────

def diff_graphs(old: dict, new: dict, lang="ru") -> list[str]:
    """Возвращает список строк-описаний изменений между двумя графами."""
    changes = []
    all_mods = set(old) | set(new)

    for mod in sorted(all_mods):
        old_deps = set(old.get(mod, []))
        new_deps = set(new.get(mod, []))

        if mod not in old and mod in new:
            changes.append(_TEXT[lang]["new"].format(mod=mod, deps=", ".join(sorted(new_deps)) or "—"))
        elif mod in old and mod not in new:
            changes.append(_TEXT[lang]["deleted"].format(mod=mod))
        else:
            added   = new_deps - old_deps
            removed = old_deps - new_deps
            if added:
                changes.append(_TEXT[lang]["added"].format(mod=mod, deps=", ".join(sorted(added))))
            if removed:
                changes.append(_TEXT[lang]["removed"].format(mod=mod, deps=", ".join(sorted(removed))))

    return changes


def arch_graph_descriptions():
    """Graph nodes/dependencies are identifiers; events use owned templates."""
    return []


def check_unregistered(graph: dict) -> list[str]:
    """⚰️ Пусто с 2026-08-03: периметр вычисляется, регистрировать нечего.

    Функция оставлена как точка вызова (её зовёт main), но больше не может
    ничего вернуть — множество `все .py минус TRACKED` пусто по построению.
    Она и была источником 2520 предупреждений, которые не читались.
    """
    return []


# ── Главный поток ─────────────────────────────────────────────────────────────

def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--lang", choices=("ru", "en"), default="ru")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--pre-commit", action="store_true")
    args = parser.parse_args(argv)
    global DRY_RUN
    DRY_RUN = args.dry_run
    try:
        return _run(args.lang)
    finally:
        if args.lang == "en":
            print("untranslated: 0")


def _run(lang):
    today = datetime.now().strftime("%Y-%m-%d")  # time-inject: ok

    # 1. Строим текущий граф
    current_graph = build_graph()

    if DRY_RUN:
        print("=== ТЕКУЩИЙ ГРАФ ЗАВИСИМОСТЕЙ ===")
        print(format_graph(current_graph, lang))
        return 0

    # 2. Загружаем сохранённый снимок
    # Independent cursors: generating RU must not consume an EN event (or vice versa).
    cache = GRAPH_CACHE if lang == "ru" else GRAPH_CACHE.with_name(".arch_graph.en.json")
    stored_graph: dict = current_graph if lang == "en" else {}
    if cache.exists():
        try:
            stored_graph = json.loads(cache.read_text())
        except Exception:
            stored_graph = {}

    # 3. Сравниваем
    changes = diff_graphs(stored_graph, current_graph, lang)

    if not changes and lang == "ru":
        print("arch_guard: граф не изменился.")
        return 0

    # 4. Документируем
    summary = "; ".join(changes[:4])
    if len(changes) > 4:
        summary += _TEXT[lang]["more"].format(count=len(changes) - 4)

    print(f"arch_guard: обнаружены изменения архитектуры ({len(changes)}):")
    for c in changes:
        print(f"  • {c}")

    written = update_arch_snapshot(current_graph, summary, today, lang)
    if lang == "en" and not written:
        return 2  # Do not consume an event before the English document accepts it.

    # 5. Сохраняем новый снимок
    if not DRY_RUN:
        cache.write_text(json.dumps(current_graph, indent=2, ensure_ascii=False))

    # 6. Предупреждения о незарегистрированных модулях
    warns = check_unregistered(current_graph)
    for w in warns:
        print(w)

    return 0


if __name__ == "__main__":
    try:
        code = main()
    except Exception as e:
        _log(f"ERROR: {e}")
        # В режиме хука — никогда не блокируем коммит
        code = 0
    sys.exit(0 if PRE_COMMIT else code)
