"""gen_key_paths.py — генератор секции КЛЮЧЕВЫЕ ПУТИ в ARCH_SNAPSHOT.md.

Wave 3-DOC v2 P5-2. Hostname-guarded (правило #8): запускать только на Studio.
Идемпотентный: повторный запуск даёт тот же результат (md5 идентичен).

Архитектура: блок между маркерами `<!-- GEN:KEY_PATHS:START -->` и
`<!-- GEN:KEY_PATHS:END -->` в ARCH_SNAPSHOT.md перезаписывается полностью.
Если маркеров нет — выпадает с ошибкой (требует ручной разметки секции
КЛЮЧЕВЫЕ ПУТИ через первый коммит).

Источник данных: интроспекция health_db._STUDIO_LOCAL_DIR + статический
inventory сервисных директорий (logs, backups, secrets, LaunchAgents).
Sources для каждого пути проверяются: если директория физически не
существует на Studio — путь помечается ⚠️.

Usage (только на Studio):
    /opt/homebrew/bin/python3.11 ~/health_scripts/gen_key_paths.py
"""
from __future__ import annotations

import argparse
import socket
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
ARCH = REPO / "ARCH_SNAPSHOT.md"
START = "<!-- GEN:KEY_PATHS:START -->"
END = "<!-- GEN:KEY_PATHS:END -->"

# Inventory: (path, description). Маркер ⚠️ ставится в build_section если
# директория физически отсутствует. Source-of-truth для путей — реальная
# FS Studio + health_db.STUDIO_HOSTNAMES const.

STUDIO_PATHS = [
    # ─── Production data (canonical, Studio local) ──────────────────────
    ("~/health/", "HEALTH_DATA_DIR (canonical после P1-1 hostname-aware)"),
    ("~/health/data/health.db", "SQLite БД, 27 таблиц (single-primary, 2026-04-24)"),
    ("~/health/daily_metrics/", "JSON по дням от import_oura.py"),
    ("~/health/reports/", "Markdown GP отчёты YYYY-MM-DD.md"),
    ("~/health/genome/", "raw 23andMe TSV (импортируется в raw_snps)"),
    ("~/health/biochemical/", "PDF лабораторных анализов"),
    ("~/health/backups/", "Ежедневные sqlite3 .backup (ротация 30д, com.larry.health.backup)"),
    ("~/health/logs/", "api.log, bot logs, per-machine"),
    ("~/health/.claude/specialists/", "Промпты MDT-специалистов (oncology.md и др.)"),

    # ─── Production code (git canonical, Studio) ────────────────────────
    ("~/health_scripts/", "Production-код, git canonical после миграции 2026-05-09"),
    ("~/health_scripts/scripts/git-hooks/pre-commit", "Pre-commit hook (P1-4, INV-DOC enforcement)"),
    ("~/health_scripts/scripts/install_hooks.sh", "Установка hook через symlink (Studio-only)"),
    ("~/health_scripts/scripts/pre_destructive_check.sh", "Manual guard перед reset/checkout/merge"),
    ("~/health_scripts/doc_inventory.yaml", "SSOT классификации .md (LIVE/archive)"),

    # ─── Secrets (не в git) ─────────────────────────────────────────────
    ("~/.health_secrets/anthropic_key", "Claude API key"),
    ("~/.health_secrets/oura_token", "Oura Ring API v2 token"),
    ("~/.health_secrets/telegram_token", "Telegram Bot API token"),
    ("~/.health_secrets/telegram_chat_id", "Целевой chat для отчётов"),
    ("~/.health_secrets/sync_token", "X-Sync-Token для bot→Studio FastAPI"),

    # ─── launchd ────────────────────────────────────────────────────────
    ("~/Library/LaunchAgents/com.larry.health.bot.plist", "Telegram бот (KeepAlive)"),
    ("~/Library/LaunchAgents/com.larry.health.api.plist", "FastAPI :8000 (KeepAlive)"),
    ("~/Library/LaunchAgents/com.larry.health.backup.plist", "Daily sqlite3 backup 03:00"),
    ("~/Library/LaunchAgents/com.larry.health.test-suite.plist", "Nightly test pyramid 00:00"),
    ("~/Library/LaunchAgents/com.larry.health.watcher.plist", "fswatch → import"),
    ("~/Library/LaunchAgents/com.larry.health.reminders-sync.plist", "macOS Reminders sync каждые 3ч"),
]

MACBOOK_PATHS = [
    ("~/health_scripts/", "Рабочая копия, полный клон: единственный писатель, коммиты только здесь (CLAUDE.md §C)"),
    ("~/health_scripts/scripts/pre_destructive_check.sh", "Pre-destructive (правило #4)"),
    # домашний префикс — «~»: абсолютный путь машины в публичной зоне — след владельца (pii_census [infra])
    (None, "облачная папка установки: реплика только для чтения (НЕ canonical, отстаёт)"),
    ("~/.infrastructure.md", "Manifest инфраструктуры (узлы, порты, Tailscale, FileVault)"),
    ("~/.health_secrets/", "Локальная копия секретов"),
    ("~/Library/LaunchAgents/com.larry.health.backup.plist", "03:00 снимок дерева в refs/backups/daily-<дата> → push на Studio; main не трогает (CLAUDE.md §1)"),
]


_TEXT = {
    "ru": {
        "heading": "## КЛЮЧЕВЫЕ ПУТИ",
        "header": "<!-- АВТОГЕНЕРИРУЕТСЯ gen_key_paths.py — не редактировать вручную. -->",
        "source": "<!-- Источник: реальная FS Studio + health_db._STUDIO_LOCAL_DIR. -->",
        "studio": "### Studio (canonical, через Tailscale; адрес — private/infra.yaml)",
        "missing": " ⚠️ отсутствует",
        "cloud": "<облачной папки нет>"
    },
    "en": {
        "heading": "## KEY PATHS",
        "header": "<!-- Generated by gen_key_paths.py; descriptions are machine-translated from the Russian source. Do not edit manually. -->",
        "source": "<!-- Source: actual Studio filesystem + health_db._STUDIO_LOCAL_DIR. -->",
        "studio": "### Studio (canonical, via Tailscale; address in private/infra.yaml)",
        "missing": " ⚠️ missing",
        "cloud": "<no cloud folder>",
        "descriptions": {
            "HEALTH_DATA_DIR (canonical после P1-1 hostname-aware)": "HEALTH_DATA_DIR (canonical after P1-1 hostname-aware)",
            "SQLite БД, 27 таблиц (single-primary, 2026-04-24)": "SQLite DB, 27 tables (single-primary, 2026-04-24)",
            "JSON по дням от import_oura.py": "Daily JSON from import_oura.py",
            "Markdown GP отчёты YYYY-MM-DD.md": "Markdown GP reports YYYY-MM-DD.md",
            "raw 23andMe TSV (импортируется в raw_snps)": "raw 23andMe TSV (imported into raw_snps)",
            "PDF лабораторных анализов": "Laboratory report PDFs",
            "Ежедневные sqlite3 .backup (ротация 30д, com.larry.health.backup)": "Daily sqlite3 .backup (30-day rotation, com.larry.health.backup)",
            "api.log, bot logs, per-machine": "api.log, bot logs, per-machine",
            "Промпты MDT-специалистов (oncology.md и др.)": "MDT specialist prompts (oncology.md etc.)",
            "Production-код, git canonical после миграции 2026-05-09": "Production code, git canonical after the 2026-05-09 migration",
            "Pre-commit hook (P1-4, INV-DOC enforcement)": "Pre-commit hook (P1-4, INV-DOC enforcement)",
            "Установка hook через symlink (Studio-only)": "Hook installation via symlink (Studio-only)",
            "Manual guard перед reset/checkout/merge": "Manual guard before reset/checkout/merge",
            "SSOT классификации .md (LIVE/archive)": "SSOT for .md classification (LIVE/archive)",
            "Claude API key": "Claude API key",
            "Oura Ring API v2 token": "Oura Ring API v2 token",
            "Telegram Bot API token": "Telegram Bot API token",
            "Целевой chat для отчётов": "Target chat for reports",
            "X-Sync-Token для bot→Studio FastAPI": "X-Sync-Token for bot→Studio FastAPI",
            "Telegram бот (KeepAlive)": "Telegram bot (KeepAlive)",
            "FastAPI :8000 (KeepAlive)": "FastAPI :8000 (KeepAlive)",
            "Daily sqlite3 backup 03:00": "Daily sqlite3 backup 03:00",
            "Nightly test pyramid 00:00": "Nightly test pyramid 00:00",
            "fswatch → import": "fswatch → import",
            "macOS Reminders sync каждые 3ч": "macOS Reminders sync every 3h",
            "Рабочая копия, полный клон: единственный писатель, коммиты только здесь (CLAUDE.md §C)": "Working copy, full clone: sole writer, commits only here (CLAUDE.md §C)",
            "Pre-destructive (правило #4)": "Pre-destructive (rule #4)",
            "облачная папка установки: реплика только для чтения (НЕ canonical, отстаёт)": "Installation cloud folder: read-only replica (NOT canonical, lags behind)",
            "Manifest инфраструктуры (узлы, порты, Tailscale, FileVault)": "Infrastructure manifest (nodes, ports, Tailscale, FileVault)",
            "Локальная копия секретов": "Local copy of secrets",
            "03:00 снимок дерева в refs/backups/daily-<дата> → push на Studio; main не трогает (CLAUDE.md §1)": "03:00 tree snapshot to refs/backups/daily-<date> → push to Studio; leaves main unchanged (CLAUDE.md §1)"
        }
    }
}
_TEXT["ru"]["descriptions"] = {desc: desc for _, desc in STUDIO_PATHS + MACBOOK_PATHS}


def key_paths_descriptions():
    """Inventory descriptions are generator-owned literals, not translation-memory data."""
    return []


def build_section(lang="ru", *, studio_paths=None, macbook_paths=None, exists=None) -> str:
    """Собирает блок между START/END маркерами."""
    text = _TEXT[lang]
    home = Path.home()
    exists = exists or Path.exists
    studio_paths = STUDIO_PATHS if studio_paths is None else studio_paths
    if macbook_paths is None:
        import infra_config
        cloud = str(infra_config.CLOUD_HEALTH_DIR or text["cloud"]).replace(str(home), "~", 1) + "/"
        macbook_paths = [(cloud if path is None else path, desc) for path, desc in MACBOOK_PATHS]
    lines = [
        START,
        "",
        text["heading"],
        text["header"],
        text["source"],
        "",
        text["studio"],
        "",
        "```",
    ]
    for raw_path, desc in studio_paths:
        # Маркер ⚠️ если путь не существует физически (Studio = self).
        abs_path = Path(str(raw_path).replace("~", str(home)))
        marker = "" if exists(abs_path) else text["missing"]
        lines.append(f"{raw_path:60s}-- {text['descriptions'][desc]}{marker}")
    lines += [
        "```",
        "",
        "### MacBook (working copy)",
        "",
        "```",
    ]
    for raw_path, desc in macbook_paths:
        lines.append(f"{raw_path:60s}-- {text['descriptions'][desc]}")
    lines += [
        "```",
        "",
        END,
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--lang", choices=("ru", "en"), default="ru")
    args = parser.parse_args(argv)
    import infra_config
    _HOSTNAME = socket.gethostname()
    if not infra_config.is_primary(_HOSTNAME):
        sys.exit(f"gen_key_paths.py: запуск только на Studio (текущий: {_HOSTNAME}). CLAUDE.md §8 canonical-only generation.")
    target = ARCH if args.lang == "ru" else ARCH.with_name("ARCH_SNAPSHOT.en.md")
    try:
        return _write_section(target, args.lang)
    finally:
        if args.lang == "en":
            print("untranslated: 0")


def _write_section(target, lang):
    if not target.exists():
        print(f"❌ {target} не найден")
        return 2

    src = target.read_text(encoding="utf-8")
    new_block = build_section(lang)

    if START in src and END in src:
        # Заменяем существующий блок.
        before, _rest = src.split(START, 1)
        _old, after = _rest.split(END, 1)
        new_src = before + new_block + after
    else:
        # Маркеров нет — это первый коммит. Ищем секцию КЛЮЧЕВЫЕ ПУТИ
        # и заменяем её целиком (вместе с заголовком).
        import re
        match = re.search(
            r"^## КЛЮЧЕВЫЕ ПУТИ\s*\n+```.*?\n```\s*\n",
            src,
            re.DOTALL | re.MULTILINE,
        )
        if not match:
            print(
                "❌ Не нашёл ни маркеров GEN:KEY_PATHS, ни секции '## КЛЮЧЕВЫЕ ПУТИ' — "
                "запусти вручную с разметкой первого коммита."
            )
            return 2
        new_src = src[:match.start()] + new_block + "\n\n" + src[match.end():]

    if new_src == src:
        print("✅ KEY_PATHS already up-to-date")
        return 0

    target.write_text(new_src, encoding="utf-8")
    print(f"✅ KEY_PATHS regenerated in {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
