#!/usr/bin/env python3.11
"""gen_testing_contracts.py — генерирует секцию «Реестр датчиков целостности»
в TESTING_CONTRACTS.md из integrity_tests.py (источник правды — код).

Зачем: TESTING_CONTRACTS ручной прозой отставал от кода на 2+ месяца (обзор
2026-07-02: не знал 4+ датчика). Список датчиков и пороги-константы теперь
генерируются из AST integrity_tests.py — дрейф невозможен, а не сигналится.

MacBook-safe: парсит ТОЛЬКО исходник (AST), БД не трогает — поэтому гоняется
в pre-commit на MacBook (get_conn на не-Studio бросает; см. run_checks Studio-only).
Пороги из system_config (БД) сюда НЕ тянем — они per-tenant и требуют Studio.

Запуск:
  python3.11 gen_testing_contracts.py            # обновить секцию
  python3.11 gen_testing_contracts.py --check    # exit 1 если секция устарела (для CI)
"""
from __future__ import annotations

import argparse
import ast
from gen_blueprint import DescriptionText
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "integrity_tests.py"
DOC = ROOT / "TESTING_CONTRACTS.md"

BEGIN = "<!-- BEGIN AUTOGEN: integrity-sensors (gen_testing_contracts.py) -->"
END = "<!-- END AUTOGEN: integrity-sensors -->"


_TEXT = {
    "ru": {
        "sensors": "### Реестр датчиков целостности ({count} шт., генерируется)",
        "source": "> Источник: `integrity_tests.py`. Таблица построена из AST — не редактировать руками, менять код. launchd 07:50 → triage 08:00.",
        "sensor_columns": "| Датчик (label) | Функция | Что проверяет |",
        "thresholds": "### Пороги-константы ({count} шт., генерируется)",
        "threshold_columns": "| Константа | Значение | Пояснение |",
    },
    "en": {
        "sensors": "### Integrity sensor registry ({count} sensors, generated)",
        "source": "> Source: `integrity_tests.py`. Built from the AST — edit the code, not this table. launchd 07:50 → triage 08:00.",
        "sensor_columns": "| Sensor (label) | Function | What it checks |",
        "thresholds": "### Threshold constants ({count} constants, generated)",
        "threshold_columns": "| Constant | Value | Explanation |",
        "header": "<!-- Generated by gen_testing_contracts.py; descriptions are machine-translated from the Russian source. -->",
    },
}


def testing_contracts_descriptions():
    """Exact Russian labels, first doc lines and escaped inline comments."""
    descriptions = DescriptionText()
    render(descriptions=descriptions)
    return descriptions.texts


def _first_doc_line(node: ast.FunctionDef) -> str:
    doc = ast.get_docstring(node) or ""
    line = doc.strip().split("\n", 1)[0].strip()
    return line or "—"


def _collect() -> tuple[list[tuple[str, str, str]], list[tuple[str, str, str]]]:
    tree = ast.parse(SRC.read_text(encoding="utf-8"), str(SRC))
    funcs = {n.name: n for n in tree.body if isinstance(n, ast.FunctionDef)}

    # 1. Регистрации check("label", fn) на верхнем уровне модуля.
    sensors: list[tuple[str, str, str]] = []
    for node in tree.body:
        if (isinstance(node, ast.Expr) and isinstance(node.value, ast.Call)
                and isinstance(node.value.func, ast.Name)
                and node.value.func.id == "check" and node.value.args):
            label_node = node.value.args[0]
            label = ast.literal_eval(label_node) if isinstance(
                label_node, ast.Constant) else "<dynamic>"
            fn = ""
            if len(node.value.args) >= 2 and isinstance(node.value.args[1], ast.Name):
                fn = node.value.args[1].id
            doc = _first_doc_line(funcs[fn]) if fn in funcs else "—"
            sensors.append((str(label), fn or "—", doc))

    # 2. Пороги-константы: UPPER_CASE = число (+ inline-комментарий как пояснение).
    src_lines = SRC.read_text(encoding="utf-8").splitlines()
    thresholds: list[tuple[str, str, str]] = []
    for node in tree.body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name)
                and isinstance(node.value, ast.Constant)
                and isinstance(node.value.value, (int, float))
                and node.targets[0].id.isupper()):
            name = node.targets[0].id
            val = node.value.value
            raw = src_lines[node.lineno - 1]
            m = re.search(r"#\s*(.+)$", raw)
            note = m.group(1).strip() if m else "—"
            thresholds.append((name, str(val), note))
    return sensors, thresholds


def render(lang="ru", *, descriptions=None) -> str:
    text = _TEXT[lang]
    descriptions = descriptions or DescriptionText(lang)
    sensors, thresholds = _collect()
    out = [BEGIN,
           "",
           text["sensors"].format(count=len(sensors)),
           "",
           text["source"],
           "",
           text["sensor_columns"],
           "|---|---|---|"]
    if lang == "en":
        out.insert(1, text["header"])
    for label, fn, doc in sensors:
        label = descriptions.cell(label)
        doc = descriptions.cell(doc.replace("|", "\\|"))
        out.append(f"| {label} | `{fn}` | {doc} |")
    out += ["",
            text["thresholds"].format(count=len(thresholds)),
            "",
            text["threshold_columns"],
            "|---|---|---|"]
    for name, val, note in thresholds:
        note = descriptions.cell(note.replace("|", "\\|"))
        out.append(f"| `{name}` | {val} | {note} |")
    out += ["", END]
    return "\n".join(out)


def _apply(text: str, block: str) -> str:
    if BEGIN in text and END in text:
        pre = text[:text.index(BEGIN)]
        post = text[text.index(END) + len(END):]
        return pre + block + post
    # Первый раз — вставляем перед разделом «## 5. ЧТО НЕ ТЕСТИРУЕТСЯ».
    anchor = "## 5. ЧТО НЕ ТЕСТИРУЕТСЯ"
    if anchor in text:
        i = text.index(anchor)
        return text[:i] + block + "\n\n---\n\n" + text[i:]
    return text.rstrip() + "\n\n" + block + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--lang", choices=("ru", "en"), default="ru")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    descriptions = DescriptionText(args.lang)
    block = render(args.lang, descriptions=descriptions)
    target = DOC if args.lang == "ru" else DOC.with_name("TESTING_CONTRACTS.en.md")
    current = target.read_text(encoding="utf-8")
    updated = _apply(current, block)
    def finish(code):
        if args.lang == "en":
            print(f"untranslated: {descriptions.untranslated}")
        return code
    if args.check:
        if updated != current:
            print(f"{target.name}: AUTOGEN-сектор устарел — "
                  "запусти python3.11 gen_testing_contracts.py")
            return finish(1)
        print(f"{target.name}: AUTOGEN актуален.")
        return finish(0)
    if updated != current:
        target.write_text(updated, encoding="utf-8")
        print(f"{target.name} обновлён (датчиков в реестре).")
    else:
        print(f"{target.name}: без изменений.")
    return finish(0)


if __name__ == "__main__":
    raise SystemExit(main())
