"""gen_arch_blocks.py — мульти-блочный генератор для ARCH_SNAPSHOT.md.

Wave 3-DOC v2 P5-3, P5-4 (опционально расширяется P5-5, P5-6).
Hostname-guarded (правило #8): запускать только на Studio.

Каждая секция — отдельная функция `build_<name>()` + маркеры в ARCH_SNAPSHOT:
- GEN:TEST_COVERAGE — таблица по слоям из последнего summary.json
- GEN:XFAIL_LIST — список @pytest.mark.xfail из AST-сканирования tests/

Usage:
    /opt/homebrew/bin/python3.11 ~/health_scripts/gen_arch_blocks.py
    /opt/homebrew/bin/python3.11 ~/health_scripts/gen_arch_blocks.py --only test_coverage

Идемпотентный: повторный запуск без изменений источников → identical md5.
"""
from __future__ import annotations

import argparse
from gen_blueprint import DescriptionText
import ast
import json
import socket
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent
ARCH = REPO / "ARCH_SNAPSHOT.md"
REPORTS_DIR = REPO / "tests" / "reports"


_TEXT = {
    "ru": {
        "coverage": "## ТЕСТОВОЕ ПОКРЫТИЕ (последний ночной прогон)",
        "coverage_header": "<!-- АВТОГЕНЕРИРУЕТСЯ gen_arch_blocks.py из tests/reports/<последний>/summary.json. -->",
        "no_data": "_Нет данных_ — `tests/reports/<YYYY-MM-DD>/summary.json` не найден.",
        "date": "**Дата:** {when}  ·  **overall_exit:** {overall_exit}",
        "coverage_columns": "| Слой | tests | failures | errors | skipped |",
        "xfail": "## XFAIL — известные регрессии под наблюдением",
        "xfail_header": "<!-- АВТОГЕНЕРИРУЕТСЯ gen_arch_blocks.py: AST-сканер @pytest.mark.xfail в tests/. -->",
        "empty": "_Список пустой._",
        "total": "**Всего:** {count}",
        "xfail_columns": "| Тест | Причина |",
        "no_reason": "_без reason_",
        "external": "## ВНЕШНИЕ ИНТЕГРАЦИИ",
        "external_header": "<!-- АВТОГЕНЕРИРУЕТСЯ gen_arch_blocks.py. Маркер ⚠️ — секрет не найден физически. -->",
        "services": "### Сервисы",
        "service_columns": "| Сервис | Секрет | Назначение | Модуль |",
        "endpoint_columns": "| Точка | URL | Назначение |",
        "domain": "## DOMAIN_SIGNALS (источник: `system_config.domain_signals.*`)",
        "domain_header": "<!-- АВТОГЕНЕРИРУЕТСЯ gen_arch_blocks.py --only domain_signals. -->",
        "domain_source": "<!-- Источник правды — БД тенанта; r (корреляция по его ряду) в документ не выносится. -->",
        "no_signals": "_нет сигналов в `system_config.domain_signals.{domain}` у этого тенанта — блок алерт-ревью конституции для домена пуст._"
    },
    "en": {
        "coverage": "## TEST COVERAGE (latest nightly run)",
        "coverage_header": "<!-- Generated by gen_arch_blocks.py from tests/reports/<latest>/summary.json; descriptions are machine-translated from the Russian source. -->",
        "no_data": "_No data_ — `tests/reports/<YYYY-MM-DD>/summary.json` not found.",
        "date": "**Date:** {when}  ·  **overall_exit:** {overall_exit}",
        "coverage_columns": "| Layer | tests | failures | errors | skipped |",
        "xfail": "## XFAIL — known regressions under observation",
        "xfail_header": "<!-- Generated by gen_arch_blocks.py: AST scan of @pytest.mark.xfail in tests/; descriptions are machine-translated from the Russian source. -->",
        "empty": "_The list is empty._",
        "total": "**Total:** {count}",
        "xfail_columns": "| Test | Reason |",
        "no_reason": "_no reason_",
        "external": "## EXTERNAL INTEGRATIONS",
        "external_header": "<!-- Generated by gen_arch_blocks.py. The ⚠️ marker means a secret file is missing; descriptions are machine-translated from the Russian source. -->",
        "services": "### Services",
        "service_columns": "| Service | Secret | Purpose | Module |",
        "endpoint_columns": "| Endpoint | URL | Purpose |",
        "domain": "## DOMAIN_SIGNALS (source: `system_config.domain_signals.*`)",
        "domain_header": "<!-- Generated by gen_arch_blocks.py --only domain_signals; descriptions are machine-translated from the Russian source. -->",
        "domain_source": "<!-- Source of truth: the tenant DB; r (correlation over tenant observations) is excluded from this document. -->",
        "no_signals": "_No signals in `system_config.domain_signals.{domain}` for this tenant — the domain constitution alert-review block is empty._",
        "purposes": {
            "AI, отчёты, чат": "AI, reports, chat",
            "сон, ВСР, активность": "sleep, HRV, activity",
            "интерфейс пользователя": "user interface",
            "целевой chat (OWNER fail-closed)": "target chat (OWNER fail-closed)",
            "bot→Studio FastAPI авторизация": "bot→Studio FastAPI authorization",
            "медицинская литература (публичный)": "medical literature (public)",
            "аннотация геномных вариантов (публичный)": "genomic variant annotation (public)",
            "trait-ассоциации (публичный)": "trait associations (public)",
            "шаги, ЧСС, вес": "steps, heart rate, weight",
            "события, поездки": "events, trips",
            "задачи пользователя": "user tasks",
            "соседний проект Flask :5001 (tailnet-only); маршрут /→:8000 снят 2026-07-06, TD-09": "neighbour project Flask :5001 (tailnet-only); route /→:8000 retired 2026-07-06, TD-09",
            "соседний проект public gateway → :9001 (allow-list reverse proxy)": "neighbour project public gateway → :9001 (allow-list reverse proxy)"
        }
    }
}


# ─── GEN:TEST_COVERAGE ─────────────────────────────────────────────────────

def _latest_summary() -> tuple[Path, dict] | None:
    """Самый свежий tests/reports/YYYY-MM-DD/summary.json."""
    if not REPORTS_DIR.exists():
        return None
    dirs = sorted(
        [p for p in REPORTS_DIR.iterdir() if p.is_dir() and p.name[:4].isdigit()],
        reverse=True,
    )
    for d in dirs:
        s = d / "summary.json"
        if s.exists():
            try:
                return s, json.loads(s.read_text(encoding="utf-8"))
            except Exception:
                continue
    return None


def build_test_coverage(lang="ru", *, descriptions=None) -> str:
    text = _TEXT[lang]
    found = _latest_summary()
    lines = [
        "<!-- GEN:TEST_COVERAGE:START -->",
        "",
        text["coverage"],
        text["coverage_header"],
        "",
    ]
    if found is None:
        lines += [
            text["no_data"],
            "",
            "<!-- GEN:TEST_COVERAGE:END -->",
        ]
        return "\n".join(lines)
    path, data = found
    when = data.get("date", path.parent.name)
    total = data.get("total", {})
    per = data.get("per_layer", {})
    overall_exit = data.get("overall_exit", "?")

    lines += [
        text["date"].format(when=when, overall_exit=overall_exit),
        "",
        text["coverage_columns"],
        "|---|---:|---:|---:|---:|",
    ]
    for layer in sorted(per.keys()):
        d = per[layer]
        lines.append(
            f"| {layer} | {d.get('tests', 0)} | {d.get('failures', 0)} "
            f"| {d.get('errors', 0)} | {d.get('skipped', 0)} |"
        )
    lines.append(
        f"| **TOTAL** | **{total.get('tests', 0)}** | **{total.get('failures', 0)}** "
        f"| **{total.get('errors', 0)}** | **{total.get('skipped', 0)}** |"
    )
    lines += ["", "<!-- GEN:TEST_COVERAGE:END -->"]
    return "\n".join(lines)


# ─── GEN:XFAIL_LIST ────────────────────────────────────────────────────────

def _scan_xfails() -> list[tuple[str, int, str]]:
    """AST-сканер: ищет @pytest.mark.xfail в tests/. Возвращает [(rel_path, line, reason)]."""
    out: list[tuple[str, int, str]] = []
    tests_dir = REPO / "tests"
    if not tests_dir.exists():
        return out
    for py in sorted(tests_dir.rglob("*.py")):
        try:
            src = py.read_text(encoding="utf-8")
            tree = ast.parse(src)
        except Exception:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                for dec in node.decorator_list:
                    if _is_xfail_decorator(dec):
                        reason = _extract_reason(dec)
                        out.append((str(py.relative_to(REPO)), node.lineno, reason))
                        break  # один маркер на функцию достаточно
    return out


def _is_xfail_decorator(dec: ast.AST) -> bool:
    """Распознаёт @pytest.mark.xfail и @pytest.mark.xfail(reason=...)."""
    target = dec
    if isinstance(dec, ast.Call):
        target = dec.func
    # pytest.mark.xfail — Attribute(value=Attribute(value=Name('pytest')), attr='xfail')
    if isinstance(target, ast.Attribute) and target.attr == "xfail":
        inner = target.value
        if isinstance(inner, ast.Attribute) and inner.attr == "mark":
            outer = inner.value
            if isinstance(outer, ast.Name) and outer.id == "pytest":
                return True
    return False


def _extract_reason(dec: ast.AST) -> str:
    if not isinstance(dec, ast.Call):
        return ""
    for kw in dec.keywords:
        if kw.arg == "reason" and isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
            # Полная первая строка; лимит применяется после перевода.
            return kw.value.value.strip().splitlines()[0]
    return ""


def build_xfail_list(lang="ru", *, descriptions=None) -> str:
    text = _TEXT[lang]
    descriptions = descriptions or DescriptionText(lang)
    xfails = _scan_xfails()
    lines = [
        "<!-- GEN:XFAIL_LIST:START -->",
        "",
        text["xfail"],
        text["xfail_header"],
        "",
    ]
    if not xfails:
        lines += [text["empty"], "", "<!-- GEN:XFAIL_LIST:END -->"]
        return "\n".join(lines)

    lines += [
        text["total"].format(count=len(xfails)),
        "",
        text["xfail_columns"],
        "|---|---|",
    ]
    for path, line, reason in xfails:
        loc = f"`{path}:{line}`"
        lines.append(f"| {loc} | {descriptions.cell(reason, limit=120) if reason else text['no_reason']} |")
    lines += ["", "<!-- GEN:XFAIL_LIST:END -->"]
    return "\n".join(lines)


# ─── GEN:EXTERNAL_INTEGRATIONS ─────────────────────────────────────────────

# Статический inventory внешних сервисов. Источник правды:
# .infrastructure.md (узлы, порты, Tailscale) + ARCH_SNAPSHOT-как-был
# (таблица интеграций). Авто-извлечь без хрупких parsers сложно — оставляю
# captured-knowledge с проверкой существования секретных файлов.
EXTERNAL_INTEGRATIONS = [
    # (service, secret_file or "", purpose, module)
    ("Anthropic Claude API", "~/.health_secrets/anthropic_key", "AI, отчёты, чат", "hai_core, gp_agent"),
    ("Oura Ring API v2", "~/.health_secrets/oura_token", "сон, ВСР, активность", "import_oura"),
    ("Telegram Bot API", "~/.health_secrets/telegram_token", "интерфейс пользователя", "telegram_bot"),
    ("Telegram chat-id", "~/.health_secrets/telegram_chat_id", "целевой chat (OWNER fail-closed)", "telegram_bot"),
    ("Studio X-Sync-Token", "~/.health_secrets/sync_token", "bot→Studio FastAPI авторизация", "telegram_bot, main"),
    ("PubMed E-utilities", "", "медицинская литература (публичный)", "pubmed_client"),
    ("MyVariant.info", "", "аннотация геномных вариантов (публичный)", "genome_annotator"),
    ("GWAS Catalog", "", "trait-ассоциации (публичный)", "genome_context"),
    ("Apple Health Export", "(iCloud XML)", "шаги, ЧСС, вес", "import_apple_health"),
    ("macOS Calendar", "(icalbuddy CLI)", "события, поездки", "calendar_client"),
    ("macOS Reminders", "(osascript)", "задачи пользователя", "task_agent, reminders_sync"),
]

# Tailscale endpoints (источник: ~/.infrastructure.md). Имя хоста в публичный документ не
# пишется (pii-scrub 2026-09-23): оно ведёт на публичную точку Funnel; значение — private/infra.yaml.
TAILSCALE_ENDPOINTS = [
    ("Private Serve :443", "https://<tailnet_hostname>/", "соседний проект Flask :5001 (tailnet-only); маршрут /→:8000 снят 2026-07-06, TD-09"),
    ("Public Funnel :10000", "https://<tailnet_hostname>:10000/mm", "соседний проект public gateway → :9001 (allow-list reverse proxy)"),
]


_TEXT["ru"]["purposes"] = {row[2]: row[2] for row in EXTERNAL_INTEGRATIONS + TAILSCALE_ENDPOINTS}


def build_external_integrations(lang="ru", *, descriptions=None) -> str:
    text = _TEXT[lang]
    home = Path.home()
    lines = [
        "<!-- GEN:EXTERNAL_INTEGRATIONS:START -->",
        "",
        text["external"],
        text["external_header"],
        "",
        text["services"],
        "",
        text["service_columns"],
        "|---|---|---|---|",
    ]
    for service, secret, purpose, module in EXTERNAL_INTEGRATIONS:
        marker = ""
        secret_display = secret or "—"
        if secret and secret.startswith("~/.health_secrets/"):
            secret_path = Path(str(secret).replace("~", str(home)))
            if not secret_path.exists():
                marker = " ⚠️"
        lines.append(f"| {service} | `{secret_display}`{marker} | {text['purposes'][purpose]} | `{module}` |")

    lines += [
        "",
        "### Tailscale endpoints",
        "",
        text["endpoint_columns"],
        "|---|---|---|",
    ]
    for name, url, purpose in TAILSCALE_ENDPOINTS:
        lines.append(f"| {name} | {url} | {text['purposes'][purpose]} |")

    lines += ["", "<!-- GEN:EXTERNAL_INTEGRATIONS:END -->"]
    return "\n".join(lines)


# Регистрация в orchestrator GENERATORS — патчим dict при импорте.


# ─── GEN:DOMAIN_SIGNALS ────────────────────────────────────────────────────

DOMAINS_INVENTORY = ["vagal_activation", "stress", "activity", "sleep", "nutrition"]


def build_domain_signals(lang="ru", *, descriptions=None, signals_by_domain=None) -> str:
    """Рендерит СОСТАВ domain_signals из system_config БД (метрика, смысл, перцентиль).

    Manual trigger: --only domain_signals. Источник правды — БД тенанта
    (`health_db.get_domain_signals(domain)`). Коэффициент r — корреляция по ряду тенанта:
    это его данные, в документ репозитория не выносится (BL-PUB-16 а, 27.09).
    """
    text = _TEXT[lang]
    descriptions = descriptions or DescriptionText(lang)
    if signals_by_domain is None:
        import health_db  # CLI guard has already run; tests supply synthetic input.
        signals_by_domain = {domain: health_db.get_domain_signals(domain) for domain in DOMAINS_INVENTORY}
    lines = [
        "<!-- GEN:DOMAIN_SIGNALS:START -->",
        "",
        text["domain"],
        text["domain_header"],
        text["domain_source"],
        "",
    ]
    for domain in DOMAINS_INVENTORY:
        signals = signals_by_domain.get(domain, [])
        if not signals:
            lines += [f"### {domain}", "", text["no_signals"].format(domain=domain), ""]
            continue
        rows = ["| metric | label | threshold_pct |", "|---|---|---:|"]
        for sig in signals:
            rows.append(f"| `{sig.get('metric', '?')}` | {descriptions.cell(sig.get('label', '?'))} | "
                        f"{sig.get('threshold_pct', '?')} |")
        lines += [f"### {domain}", ""] + rows + [""]
    lines.append("<!-- GEN:DOMAIN_SIGNALS:END -->")
    return "\n".join(lines)


# ─── orchestrator ──────────────────────────────────────────────────────────

GENERATORS = {
    "test_coverage": ("<!-- GEN:TEST_COVERAGE:START -->", "<!-- GEN:TEST_COVERAGE:END -->", build_test_coverage),
    "xfail_list": ("<!-- GEN:XFAIL_LIST:START -->", "<!-- GEN:XFAIL_LIST:END -->", build_xfail_list),
    "external_integrations": ("<!-- GEN:EXTERNAL_INTEGRATIONS:START -->", "<!-- GEN:EXTERNAL_INTEGRATIONS:END -->", build_external_integrations),
    "domain_signals": ("<!-- GEN:DOMAIN_SIGNALS:START -->", "<!-- GEN:DOMAIN_SIGNALS:END -->", build_domain_signals),
}


def arch_blocks_descriptions(only=None, *, signals_by_domain=None):
    """Collect full Russian strings before rendering limits; supply signals to avoid a DB read.

    `only="xfail_list"` needs source files only. With no selection both data-bearing
    blocks are collected; inventory prose is owned by this generator's literal table.
    """
    descriptions = DescriptionText()
    if only in (None, "xfail_list"):
        build_xfail_list(descriptions=descriptions)
    if only in (None, "domain_signals"):
        build_domain_signals(descriptions=descriptions, signals_by_domain=signals_by_domain)
    return descriptions.texts


def _apply_block(src: str, start: str, end: str, new_block: str) -> tuple[str, bool]:
    """Возвращает (new_src, changed). Если маркеров нет — добавляет в конец файла."""
    if start in src and end in src:
        before, _rest = src.split(start, 1)
        _old, after = _rest.split(end, 1)
        new_src = before + new_block + after
    else:
        # Первый коммит: добавляем в конец.
        new_src = src.rstrip() + "\n\n---\n\n" + new_block + "\n"
    return new_src, new_src != src


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--only", choices=list(GENERATORS.keys()), help="Запустить только один блок")
    parser.add_argument("--lang", choices=("ru", "en"), default="ru")
    args = parser.parse_args(argv)
    import infra_config
    hostname = socket.gethostname()
    if not infra_config.is_primary(hostname):
        sys.exit(f"gen_arch_blocks.py: запуск только на Studio (текущий: {hostname}). CLAUDE.md §8.")
    target = ARCH if args.lang == "ru" else ARCH.with_name("ARCH_SNAPSHOT.en.md")
    descriptions = DescriptionText(args.lang)
    try:
        return _write_blocks(target, args.only, args.lang, descriptions)
    finally:
        if args.lang == "en":
            print(f"untranslated: {descriptions.untranslated}")


def _write_blocks(target, only, lang, descriptions):
    if not target.exists():
        print(f"❌ {target} not found")
        return 2

    targets = [only] if only else list(GENERATORS.keys())
    src = target.read_text(encoding="utf-8")
    total_changed = 0
    for name in targets:
        start, end, builder = GENERATORS[name]
        block = builder(lang, descriptions=descriptions)
        src, changed = _apply_block(src, start, end, block)
        if changed:
            total_changed += 1
            print(f"✅ {name} regenerated")
        else:
            print(f"✅ {name} already up-to-date")

    if total_changed:
        target.write_text(src, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
