"""gen_schedule.py — генератор секции РАСПИСАНИЕ в ARCH_SNAPSHOT.md из .plist'ов.

Wave 3-DOC v2 P5-1. Hostname-guarded (правило #8): запускать только на Studio,
поскольку plist'ы лежат локально в ~/Library/LaunchAgents/.

Парсит все com.larry.health.*.plist через plistlib и рендерит таблицу с:
- расписанием (StartCalendarInterval / StartInterval / KeepAlive / WatchPaths)
- модулем (ProgramArguments[1])

Edge-cases:
- KeepAlive: bool True или dict (с условиями). bool → "KeepAlive".
- StartCalendarInterval: dict или list[dict] (несколько триггеров). Все
  рендерятся в одну строку через '; '.
- WatchPaths: путь(и) для fswatch → 'по событию'.

Usage:
    /opt/homebrew/bin/python3.11 ~/health_scripts/gen_schedule.py
"""
from __future__ import annotations

import argparse
import plistlib
import socket
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent
ARCH = REPO / "ARCH_SNAPSHOT.md"
LAUNCHD_DIR = Path.home() / "Library" / "LaunchAgents"

START = "<!-- GEN:SCHEDULE:START -->"
END = "<!-- GEN:SCHEDULE:END -->"

WEEKDAY = {0: "Вс", 1: "Пн", 2: "Вт", 3: "Ср", 4: "Чт", 5: "Пт", 6: "Сб"}


_TEXT = {
    "ru": {
        "heading": "## РАСПИСАНИЕ launchd (Studio)",
        "header": "<!-- АВТОГЕНЕРИРУЕТСЯ gen_schedule.py из ~/Library/LaunchAgents/com.larry.health.*.plist. -->",
        "note": "<!-- Не редактировать вручную. -->",
        "columns": "| Label | Расписание | Модуль |",
        "weekdays": WEEKDAY,
        "day": "{n}-го", "hours": "каждые {n}ч", "minutes": "каждые {n}мин",
        "seconds": "каждые {n}с", "watch": "по событию (WatchPaths)",
    },
    "en": {
        "heading": "## launchd SCHEDULE (Studio)",
        "header": "<!-- Generated by gen_schedule.py from ~/Library/LaunchAgents/com.larry.health.*.plist; descriptions are machine-translated from the Russian source. -->",
        "note": "<!-- Do not edit manually. -->",
        "columns": "| Label | Schedule | Module |",
        "weekdays": dict(enumerate(("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"))),
        "day": "day {n}", "hours": "every {n}h", "minutes": "every {n}min",
        "seconds": "every {n}s", "watch": "on event (WatchPaths)",
    },
}


def schedule_descriptions():
    """Plist labels/modules are identifiers; all schedule prose is generator-owned."""
    return []


def _fmt_calendar(ci, lang="ru") -> str:
    """StartCalendarInterval → читаемое расписание."""
    if isinstance(ci, list):
        return "; ".join(_fmt_calendar(c, lang) for c in ci)
    parts = []
    if "Weekday" in ci:
        parts.append(_TEXT[lang]["weekdays"].get(ci["Weekday"], f"wd{ci['Weekday']}"))
    if "Day" in ci:
        parts.append(_TEXT[lang]["day"].format(n=ci["Day"]))
    if "Hour" in ci:
        h = ci["Hour"]
        m = ci.get("Minute", 0)
        parts.append(f"{h:02d}:{m:02d}")
    elif "Minute" in ci:
        parts.append(f"*:{ci['Minute']:02d}")
    return " ".join(parts) if parts else "?"


def _fmt_interval(seconds: int, lang="ru") -> str:
    """StartInterval (секунды) → читаемое."""
    if seconds % 3600 == 0:
        return _TEXT[lang]["hours"].format(n=seconds // 3600)
    if seconds % 60 == 0:
        return _TEXT[lang]["minutes"].format(n=seconds // 60)
    return _TEXT[lang]["seconds"].format(n=seconds)


def _fmt_schedule(plist: dict, lang="ru") -> str:
    """Возвращает строку расписания для одной plist."""
    parts = []
    if "StartCalendarInterval" in plist:
        parts.append(_fmt_calendar(plist["StartCalendarInterval"], lang))
    if "StartInterval" in plist:
        parts.append(_fmt_interval(plist["StartInterval"], lang))
    if "WatchPaths" in plist:
        parts.append(_TEXT[lang]["watch"])
    ka = plist.get("KeepAlive")
    if isinstance(ka, bool) and ka:
        parts.append("KeepAlive")
    elif isinstance(ka, dict):
        parts.append(f"KeepAlive {list(ka.keys())}")
    if "RunAtLoad" in plist and plist["RunAtLoad"] and not parts:
        parts.append("RunAtLoad")
    return "; ".join(parts) if parts else "—"


def _module_short(plist: dict) -> str:
    """ProgramArguments → краткое имя модуля."""
    pa = plist.get("ProgramArguments") or []
    if not pa:
        prog = plist.get("Program", "")
        return Path(prog).name if prog else "?"
    # ProgramArguments[0] — обычно python3.11; [1] — путь к .py
    for arg in pa:
        if isinstance(arg, str) and (arg.endswith(".py") or arg.endswith(".sh")):
            return Path(arg).name
    return Path(pa[0]).name


def build_section(lang="ru") -> str:
    text = _TEXT[lang]
    plist_files = sorted(LAUNCHD_DIR.glob("com.larry.health.*.plist"))
    rows = []
    for p in plist_files:
        try:
            with p.open("rb") as f:
                data = plistlib.load(f)
        except Exception as e:
            rows.append((p.stem, f"⚠️ parse error: {e}", "?"))
            continue
        label = data.get("Label", p.stem)
        rows.append((label, _fmt_schedule(data, lang), _module_short(data)))

    lines = [
        START,
        "",
        text["heading"],
        text["header"],
        text["note"],
        "",
        text["columns"],
        "|---|---|---|",
    ]
    for label, sched, mod in rows:
        lines.append(f"| `{label}` | {sched} | `{mod}` |")
    lines += ["", END]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--lang", choices=("ru", "en"), default="ru")
    args = parser.parse_args(argv)
    import infra_config
    _HOSTNAME = socket.gethostname()
    if not infra_config.is_primary(_HOSTNAME):
        sys.exit(f"gen_schedule.py: запуск только на Studio (текущий: {_HOSTNAME}). CLAUDE.md §8.")
    target = ARCH if args.lang == "ru" else ARCH.with_name("ARCH_SNAPSHOT.en.md")
    try:
        return _write_section(target, args.lang)
    finally:
        if args.lang == "en":
            print("untranslated: 0")


def _write_section(target, lang):
    if not target.exists():
        print(f"❌ {target} not found")
        return 2
    src = target.read_text(encoding="utf-8")
    new_block = build_section(lang)
    if START in src and END in src:
        before, _rest = src.split(START, 1)
        _old, after = _rest.split(END, 1)
        new_src = before + new_block + after
    else:
        # Маркеров нет — ищем «## РАСПИСАНИЕ» и заменяем секцию.
        import re
        # Старая секция в ARCH_SNAPSHOT — таблица под "## РАСПИСАНИЕ".
        match = re.search(
            r"^## РАСПИСАНИЕ[^\n]*\n.*?(?=\n^---|\n^## )",
            src,
            re.DOTALL | re.MULTILINE,
        )
        if not match:
            print("❌ Не нашёл секцию '## РАСПИСАНИЕ' для замены — добавь маркеры вручную")
            return 2
        new_src = src[:match.start()] + new_block + "\n\n" + src[match.end():]
    if new_src == src:
        print("✅ SCHEDULE already up-to-date")
        return 0
    target.write_text(new_src, encoding="utf-8")
    print(f"✅ SCHEDULE regenerated in {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
