#!/usr/bin/env python3.11
"""gen_blueprint.py — автообновление МОДУЛЬНОГО РЕЕСТРА в ARCH_SNAPSHOT.md.

Имя историческое: до 2026-08-02 скрипт писал ещё и §25 BLUEPRINT из рукописного
списка MODULES (снят, см. ниже). Осталась одна работа — AST-обход дерева.

Запуск:
  python3.11 gen_blueprint.py           # обновить ARCH_SNAPSHOT
  python3.11 gen_blueprint.py --dry-run # показать что изменится, не писать

В pre-commit:
  python3.11 gen_blueprint.py && git add ARCH_SNAPSHOT.md
"""
import argparse
import ast
import desc_translation
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT          = Path(__file__).parent
ARCH_SNAPSHOT = ROOT / "ARCH_SNAPSHOT.md"
DRY_RUN       = "--dry-run" in sys.argv

# ── §25 BLUEPRINT снят 2026-08-02 (решение владельца) ────────────────────────
# Здесь жил MODULES — рукописный список из 41 пары (имя, описание), по которому
# строился раздел «Модульная карта (автогенерация)» в BLUEPRINT.md. Генерировался
# только счётчик строк; сам список вёлся руками и разошёлся с деревом: одного файла
# не существовало (knowledge_engine.py), integrity_tests был описан как «15 проверок»
# при 121, покрытие 41 из 318 .py. Слово «автогенерация» в заголовке гасило
# подозрение читателя. Живая карта строится ниже AST-обходом — update_arch_snapshot().


_ARCH_START = "<!-- GEN:MODULE_REGISTRY:START -->"
_ARCH_END   = "<!-- GEN:MODULE_REGISTRY:END -->"

_ARCH_LAYERS = [
    ("СЛОЙ ДАННЫХ",      ["health_db.py",  # фасад (ядро + ре-экспорт доменов, Поток C)
                           "agent_reports_db.py", "alerts_db.py", "assessments_db.py",
                           "checkins_db.py", "config_db.py", "constitutions_db.py",
                           "consult_sessions_db.py", "consultations_db.py", "dashboard_db.py",
                           "doc_reviews_db.py", "events_db.py", "experiments_db.py",
                           "field_reviews_db.py", "genome_db.py", "hae_db.py",
                           "hypotheses_db.py", "import_status_db.py", "labs_db.py",
                           "memory_db.py", "metrics_db.py", "periods_db.py",
                           "problems_db.py", "profile_db.py", "proposals_db.py",
                           "protocols_db.py", "rules_db.py", "tasks_db.py",
                           "treatment_db.py", "workouts_db.py"]),
    ("СЛОЙ ИНТЕЛЛЕКТА",  ["health_ai.py", "hai_core.py", "hai_context.py",
                           "hai_analysis.py", "hai_hypotheses.py",
                           "hai_reports.py", "hai_chat.py"]),
    ("ГЕНОМ",            ["genome_parser.py", "genome_annotator.py",
                           "genome_context.py", "genome_update_agent.py"]),
    ("GP И СПЕЦИАЛИСТЫ", ["gp_agent.py", "gp_context.py", "wellally_consult.py",
                           "lifestyle_agents.py", "safety_net.py"]),
    # knowledge_engine.py пережил снятие MODULES (выше) и в этом списке — файла нет;
    # удалён 29.09, сторож tests/consistency/test_arch_generated_refs.py.
    ("ЗАДАЧИ И ЧЕКИНЫ",  ["task_agent.py", "checkin_agent.py", "reminders_sync.py"]),
    ("ИМПОРТ ДАННЫХ",    ["import_oura.py", "import_apple_health.py",
                           "import_hr_activity.py", "import_medical_docs.py",
                           "import_all.py", "calendar_client.py"]),
    ("АВТОДОКУМЕНТАЦИЯ", ["doc_agent.py", "run_checks.sh", "integrity_tests.py",
                           "check_contracts.py", "smoke_tests.py", "gen_blueprint.py"]),
    ("ИНТЕРФЕЙС",        ["telegram_bot.py"]),
]


_TEXT = {
    "ru": {
        "heading": "## МОДУЛЬНЫЙ РЕЕСТР",
        "header": "<!-- Авто-генерировано gen_blueprint.py {today} -->",
        "missing": "файл не найден",
        "layers": ("СЛОЙ ДАННЫХ", "СЛОЙ ИНТЕЛЛЕКТА", "ГЕНОМ", "GP И СПЕЦИАЛИСТЫ",
                   "ЗАДАЧИ И ЧЕКИНЫ", "ИМПОРТ ДАННЫХ", "АВТОДОКУМЕНТАЦИЯ", "ИНТЕРФЕЙС"),
    },
    "en": {
        "heading": "## MODULE REGISTRY",
        "header": "<!-- Generated by gen_blueprint.py {today}; descriptions are machine-translated from the Russian source. -->",
        "missing": "file not found",
        "layers": ("DATA LAYER", "INTELLIGENCE LAYER", "GENOME", "GP AND SPECIALISTS",
                   "TASKS AND CHECK-INS", "DATA IMPORT", "AUTOMATED DOCUMENTATION", "INTERFACE"),
    },
}


class DescriptionText:
    """One rendering pass: exact translation keys, collected sources, missing occurrences.

    Shared by the three generators with data-derived descriptions. RU collection uses
    the same rendering path without consulting translation memory or calling a model.
    """
    def __init__(self, lang="ru"):
        if lang not in ("ru", "en"):
            raise ValueError(f"Unsupported language: {lang}")
        self.lang = lang
        self.texts = []
        self.untranslated = 0

    def text(self, source, *, limit=None):
        """Collect and translate the full source, then apply the rendering limit."""
        source = str(source)
        if re.search(r"[А-Яа-яЁё]", source):
            self.texts.append(source)
        if self.lang == "ru":
            return source[:limit]
        translated = desc_translation.english(source)
        if translated is None:
            self.untranslated += 1
            return source[:limit] + " ⟨untranslated⟩"
        return translated[:limit]

    def cell(self, source, *, limit=None):
        """Escape table separators after lookup, without changing the memory key."""
        value = self.text(source, limit=limit)
        if self.lang == "en":
            return re.sub(r"(?<!\\)\|", lambda match: r"\|", value)
        return value


def blueprint_descriptions():
    """Full Russian first lines, before the 80/65-character rendering limits."""
    descriptions = DescriptionText()
    _build_arch_registry(descriptions=descriptions)
    return descriptions.texts


def _first_line(s: str) -> str:
    return s.splitlines()[0].strip() if s else ""


def _build_arch_registry(lang="ru", *, descriptions=None) -> str:
    text = _TEXT[lang]
    descriptions = descriptions or DescriptionText(lang)
    today = date.today().isoformat()  # time-inject: ok
    lines = [
        text["heading"],
        text["header"].format(today=today),
        "",
    ]
    for layer, files in _ARCH_LAYERS:
        layer = dict(zip(_TEXT["ru"]["layers"], text["layers"]))[layer]
        lines += [f"### {layer}", "```", ""]
        for fname in files:
            path = ROOT / fname
            if not path.exists():
                lines += [f"{fname}  # {text['missing']}", ""]
                continue
            doc_first, funcs = "", []
            if fname.endswith(".py"):
                try:
                    tree = ast.parse(path.read_text())
                    doc_first = _first_line(ast.get_docstring(tree) or "")
                    seen: set = set()
                    for node in ast.walk(tree):
                        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                            if node.name.startswith("_") or node.name in seen:
                                continue
                            seen.add(node.name)
                            args = [a.arg for a in node.args.args
                                    if a.arg not in ("self", "cls")]
                            fd_s = _first_line(ast.get_docstring(node) or "")
                            pfx  = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
                            funcs.append((f"  {pfx}{node.name}({', '.join(args[:4])})", fd_s))
                        elif isinstance(node, ast.ClassDef):
                            if not node.name.startswith("_") and node.name not in seen:
                                seen.add(node.name)
                                funcs.append((f"  class {node.name}", ""))
                except Exception:
                    pass
            lines.append(f"{fname}  # {descriptions.text(doc_first, limit=80)}" if doc_first else fname)
            # Translate outside the AST error handler: a memory failure must not drop functions.
            lines.extend(signature + (" — " + descriptions.text(doc, limit=65) if doc else "")
                         for signature, doc in funcs)
            lines.append("")
        lines += ["```", ""]
    return "\n".join(lines)


def update_arch_snapshot(lang="ru", *, descriptions=None) -> bool:
    """Перезаписывает раздел МОДУЛЬНЫЙ РЕЕСТР в ARCH_SNAPSHOT.md между GEN-маркерами."""
    target = ARCH_SNAPSHOT if lang == "ru" else ARCH_SNAPSHOT.with_name("ARCH_SNAPSHOT.en.md")
    if not target.exists():
        print(f"{target.name} не найден: {target}")
        return False
    content = target.read_text(encoding="utf-8")
    if _ARCH_START not in content or _ARCH_END not in content:
        print(f"GEN-маркеры не найдены в {target.name} — пропускаем")
        return False
    new_body    = _ARCH_START + "\n\n" + _build_arch_registry(lang, descriptions=descriptions) + "\n" + _ARCH_END
    pattern     = re.escape(_ARCH_START) + r".*?" + re.escape(_ARCH_END)
    # Preserve the legacy RU replacement semantics; EN text can contain backslashes.
    replacement = new_body if lang == "ru" else lambda match: new_body
    new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)
    if new_content == content:
        print(f"{target.name} не изменился.")
        return False
    if DRY_RUN:
        print(f"--- DRY RUN: {target.stem} не записан ---")
        return False
    target.write_text(new_content, encoding="utf-8")
    print(f"✅ {target.name} обновлён ({len(new_content.splitlines())} строк)")
    return True


# ── Точка входа ───────────────────────────────────────────────────────────────

def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--lang", choices=("ru", "en"), default="ru")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    global DRY_RUN
    DRY_RUN = args.dry_run
    descriptions = DescriptionText(args.lang)
    changed = update_arch_snapshot(args.lang, descriptions=descriptions)
    if changed:
        target = "ARCH_SNAPSHOT.md" if args.lang == "ru" else "ARCH_SNAPSHOT.en.md"
        print(f"Добавь в коммит:  git add {target}")
    if args.lang == "en":
        print(f"untranslated: {descriptions.untranslated}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
