"""Карта проекта пересобрана после последнего закрытия нити (arch-en-gen, 29.09).

ЧТО ДОКАЗЫВАЕТСЯ. Датчик звенит, когда штамп реестра модулей старше последнего слияния нити
больше чем на сутки (пересборка при закрытии не прошла), молчит на свежем штампе, считает
пояснения без перевода в английских справочниках. Слияние — на НАСТОЯЩЕМ git мини-репозитория.
ЧЕГО НЕ ДОКАЗЫВАЕТСЯ. Что содержимое блоков правдиво — это суд генераторов и их сторожей.
"""
import os
import subprocess

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.host_only]


def _git(repo, *args, when="2026-09-20T12:00:00"):
    env = {**os.environ, "GIT_COMMITTER_DATE": when, "GIT_AUTHOR_DATE": when}
    subprocess.run(["git", "-C", str(repo), "-c", "user.name=t", "-c", "user.email=t@t", *args],
                   check=True, capture_output=True, env=env)


@pytest.fixture
def repo(tmp_path):
    r = tmp_path / "r"; r.mkdir()
    _git(r, "init", "-q", "-b", "main")
    (r / "a.py").write_text("x = 1\n"); _git(r, "add", "."); _git(r, "commit", "-q", "-m", "начало")
    _git(r, "checkout", "-q", "-b", "thread/t")
    (r / "a.py").write_text("x = 2\n"); _git(r, "commit", "-q", "-am", "x")
    _git(r, "checkout", "-q", "main")
    _git(r, "merge", "-q", "--no-ff", "-m", "Merge branch 'thread/t'", "thread/t", when="2026-09-25T12:00:00")
    return r


def _write(repo, ru_date, en_date, untranslated=0):
    (repo / "ARCH_SNAPSHOT.md").write_text(f"<!-- Авто-генерировано gen_blueprint.py {ru_date} -->\n", encoding="utf-8")
    (repo / "ARCH_SNAPSHOT.en.md").write_text(
        f"<!-- Generated by gen_blueprint.py {en_date}; descriptions are machine-translated -->\n"
        + "x ⟨untranslated⟩\n" * untranslated, encoding="utf-8")


def _sensor(monkeypatch, root):
    import integrity_tests as it
    cap = []
    monkeypatch.setattr(it, "warn", lambda n, d="": cap.append((n, d)))
    return it.check_arch_map_fresh(root=root), cap


def test_stale_stamp_after_merge_rings(repo, monkeypatch):
    _write(repo, "2026-09-20", "2026-09-25")
    res, cap = _sensor(monkeypatch, repo)
    assert res["stale"] == 1 and len(cap) == 1 and "ARCH_SNAPSHOT.md" in cap[0][1]


def test_fresh_stamp_is_silent_and_one_day_is_tolerated(repo, monkeypatch):
    _write(repo, "2026-09-24", "2026-09-25")
    res, cap = _sensor(monkeypatch, repo)
    assert cap == [] and res == {"last_merge": "2026-09-25", "stale": 0, "untranslated": 0}


def test_untranslated_descriptions_are_counted(repo, monkeypatch):
    _write(repo, "2026-09-25", "2026-09-25", untranslated=3)
    res, cap = _sensor(monkeypatch, repo)
    assert res["untranslated"] == 3 and len(cap) == 1 and "3" in cap[0][0]


def test_missing_stamp_rings(repo, monkeypatch):
    _write(repo, "2026-09-25", "2026-09-25")
    (repo / "ARCH_SNAPSHOT.en.md").write_text("no stamp\n", encoding="utf-8")
    res, cap = _sensor(monkeypatch, repo)
    assert res["stale"] == 1 and "штампа" in cap[0][1]
