"""genome_intake: геном из входящих тенанта → genome_pipeline (нить document-intake, 24.09).

Форматы — по описаниям производителей (замер 24.09): 23andMe TSV, AncestryDNA (две колонки
аллелей, хромосомы 23–26, «0» = нет вызова), MyHeritage/FTDNA (CSV в кавычках), tellmeGen
(zip с CSV, пропуск «–»). Данные синтетические.
"""
from __future__ import annotations

import zipfile
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

N = 30


def _23andme(p: Path, double_tab=False) -> Path:
    sep = "\t\t" if double_tab else "\t"
    body = "".join(f"rs{i}{sep}1\t{1000 + i}\tAG\n" for i in range(N))
    p.write_text("# This data file generated by 23andMe\n# file_id: X1\n"
                 "# rsid\tchromosome\tposition\tgenotype\n" + body + "i700\tMT\t50\tA\n")
    return p


def _ancestry(p: Path) -> Path:
    body = "".join(f"rs{i}\t23\t{i + 5}\tA\tG\n" for i in range(N))
    p.write_text("#AncestryDNA raw data\nrsid\tchromosome\tposition\tallele1\tallele2\n"
                 + body + "rs999\t26\t77\t0\t0\n")
    return p


def _myheritage(p: Path) -> Path:
    body = "".join(f'"rs{i}","2","{i + 9}","CT"\n' for i in range(N))
    p.write_text('# MyHeritage DNA raw data.\nRSID,CHROMOSOME,POSITION,RESULT\n' + body)
    return p


def _tellmegen_zip(p: Path, member="tellmegen_raw.csv") -> Path:
    body = "".join(f"rs{i},X,{i + 3},GG\n" for i in range(N))
    with zipfile.ZipFile(p, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(member, "rsid,chromosome,position,genotype\n" + body + "rs998,1,5,–\n")
    return p


@pytest.mark.parametrize("make,fmt,first", [
    (_23andme, "23andme_like", ("rs0", "1", 1000, "AG")),
    (_ancestry, "ancestry", ("rs0", "X", 5, "AG")),
    (_myheritage, "myheritage_ftdna", ("rs0", "2", 9, "CT")),
    (_tellmegen_zip, "tellmegen_csv", ("rs0", "X", 3, "GG")),
])
def test_formats_recognized_and_normalized(tmp_path, make, fmt, first):
    import genome_intake as gi
    src = make(tmp_path / "raw.bin")
    k = gi.sniff(src)
    assert k and k["supported"] and k["format"] == fmt, k
    out = tmp_path / "norm.txt"
    rows, file_id = gi._normalize(src, k["member"], out)
    assert rows >= N and file_id.startswith("sha256:")
    import genome_parser
    parsed = genome_parser.parse_tsv(out)           # тот самый парсер конвейера S1
    assert len(parsed) == rows
    assert (parsed[0]["rsid"], parsed[0]["chromosome"], parsed[0]["position"],
            parsed[0]["genotype"]) == first
    nocalls = [r for r in parsed if r["rsid"] in ("rs999", "rs998")]
    assert all(r["genotype"] == "--" for r in nocalls)
    assert {r["chromosome"] for r in parsed if r["rsid"] == "rs999"} <= {"MT"}


def test_double_tab_23andme(tmp_path):
    import genome_intake as gi
    src = _23andme(tmp_path / "g.txt", double_tab=True)
    rows, _ = gi._normalize(src, None, tmp_path / "n.txt")
    assert rows == N + 1


@pytest.mark.parametrize("content", [
    "Выписка из истории болезни\nДиагноз: ...\n" * 50,
    "rs1\t1\t100\tAG\n" * 3,                        # слишком мало строк — не геном
])
def test_not_genome(tmp_path, content):
    import genome_intake as gi
    p = tmp_path / "x.txt"
    p.write_text(content)
    assert gi.sniff(p) is None


def test_vcf_plain_and_gz_are_accepted_fastq_and_zipped_vcf_are_not(tmp_path):
    """28.09: VCF полного генома принимается (решение владельца), в том числе .vcf.gz —
    сжатие узнаётся по сигнатуре. VCF внутри zip — нет: распаковка в память на гигабайты."""
    import gzip
    import zipfile
    import genome_intake as gi
    body = "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\n"
    p = tmp_path / "x.vcf"
    p.write_text(body)
    assert gi.sniff(p) == {"format": "vcf", "supported": True, "member": None}
    g = tmp_path / "y.bin"
    with gzip.open(g, "wt") as fh:
        fh.write(body + "chr1\t1\t.\tA\tG\n" * 50_000)   # больше окна сниффа: усечённый gzip
    assert gi.sniff(g) == {"format": "vcf", "supported": True, "member": None}
    z = tmp_path / "v.zip"
    with zipfile.ZipFile(z, "w") as zf:
        zf.writestr("genome.vcf", body)
    assert gi.sniff(z)["supported"] is False and gi.sniff(z)["format"] == "vcf_in_zip"


def test_zip_member_name_never_becomes_a_path(tmp_path):
    """zip-slip: имя члена «../../evil.csv» не должно породить файл вне out."""
    import genome_intake as gi
    src = _tellmegen_zip(tmp_path / "a.zip", member="../../evil.csv")
    k = gi.sniff(src)
    gi._normalize(src, k["member"], tmp_path / "n.txt")
    assert not (tmp_path.parent.parent / "evil.csv").exists()
    assert sorted(x.name for x in tmp_path.iterdir()) == ["a.zip", "n.txt"]


def test_zip_bomb_is_capped(tmp_path, monkeypatch):
    import genome_intake as gi
    src = _tellmegen_zip(tmp_path / "a.zip")
    monkeypatch.setattr(gi, "MAX_BYTES", 100)
    with pytest.raises(ValueError):
        gi._normalize(src, gi.sniff(src)["member"], tmp_path / "n.txt")


def test_process_pending_spawns_once_and_notices_dead_run(tmp_path, monkeypatch):
    import genome_intake as gi
    told = []
    monkeypatch.setattr(gi, "_tell", lambda text, **kw: told.append(text))
    _23andme(tmp_path / "genome.txt")
    (tmp_path / "scan.pdf").write_bytes(b"%PDF-1.4")
    (tmp_path / "x.fastq").write_text("@r1\nACGT\n+\nIIII\n@r2\nACGT\n+\nIIII\n")
    spawned = []
    def spawn(p):
        spawned.append(p.name)
        return 999_999_999                          # такого pid нет → «процесс умер»
    assert gi.process_pending(tmp_path, spawn=spawn) == 2
    assert spawned == ["genome.txt"]
    assert gi._state(tmp_path / "x.fastq")["status"] == "unsupported"
    gi.process_pending(tmp_path, spawn=spawn)      # второй проход: мёртвый pid → громко
    assert spawned == ["genome.txt"]
    assert gi._state(tmp_path / "genome.txt")["status"] == "failed"
    assert told and "оборвалась" in told[-1]


def test_run_one_loads_raw_snps_then_refuses_second(db, tmp_path, monkeypatch):
    import genome_intake as gi, genome_pipeline, genome_parser, infra_config
    told = []
    monkeypatch.setattr(gi, "_tell", lambda text, **kw: told.append(text))
    monkeypatch.setattr(infra_config, "is_primary", lambda: True)
    got = []
    def fake_pipeline(filepath=None, **_):          # только S1: сеть и модель тесту не нужны
        got.append(filepath)
        genome_parser.import_raw_genome(Path(filepath))
        return {"raw_snps": N + 1}
    monkeypatch.setattr(genome_pipeline, "run_pipeline", fake_pipeline)
    src = _23andme(tmp_path / "genome.txt")
    res = gi.run_one(src)
    assert res["status"] == "done" and res["rows"] == N + 1, res
    with db.conn() as c:
        assert c.execute("SELECT COUNT(*) FROM raw_snps").fetchone()[0] == N + 1
    assert "Геном загружен" in told[-1]
    res2 = gi.run_one(_ancestry(tmp_path / "other.txt"))
    assert res2["status"] == "already_loaded" and len(got) == 1
    assert "уже загружен" in told[-1]


def test_bot_receipt_recognizes_genome_by_content(tmp_path):
    from handlers.messages import _receipt_text
    p = _tellmegen_zip(tmp_path / "raw.zip")
    assert "исходные данные генетического теста" in _receipt_text(p.name, p)
    v = tmp_path / "a.vcf"
    v.write_text("##fileformat=VCFv4.2\n")
    assert "исходные данные генетического теста" in _receipt_text(v.name, v)
    f = tmp_path / "a.fastq"
    f.write_text("@r1\nACGT\n+\nIIII\n@r2\nACGT\n+\nIIII\n")
    assert "fastq" in _receipt_text(f.name, f) and "tellmeGen" in _receipt_text(f.name, f)



def test_run_one_hands_vcf_to_its_pipeline_and_names_foreign_genome(tmp_path, monkeypatch):
    """VCF идёт в vcf_import_pipeline своим процессом; чужой геном человек видит словами."""
    import subprocess
    import genome_intake as gi, infra_config
    told, calls = [], []
    monkeypatch.setattr(gi, "_tell", told.append)
    monkeypatch.setattr(infra_config, "is_primary", lambda: True)
    v = tmp_path / "wgs.vcf.gz"
    v.write_bytes(b"\x1f\x8b")
    gi._set_state(v, status="queued", format="vcf", member=None)

    def ok(args, **kw):
        calls.append(args)
        return subprocess.CompletedProcess(args, 0)
    monkeypatch.setattr(gi.subprocess, "run", ok)
    assert gi.run_one(v)["status"] == "done"
    assert calls[0][-4:] == ["--phase", "all", "--vcf", str(v)]
    assert "полный геном" in told[0] and "разобран" in told[-1]

    def foreign(args, stdout=None, **kw):
        stdout.write("vcf_import_pipeline.GenomeIdentityError: 900 из 1000 позиций\n")
        return subprocess.CompletedProcess(args, 1)
    gi._set_state(v, status="queued", format="vcf", member=None)
    monkeypatch.setattr(gi.subprocess, "run", foreign)
    assert gi.run_one(v)["status"] == "failed"
    assert "другого человека" in told[-1]


def test_chip_identity_fallback_mirrors_the_seed(db, monkeypatch):
    """Порог «чужой геном» живёт в system_config (решение владельца 29.09); резерв в коде —
    ЗЕРКАЛО сида, не вторая норма: разойдись они — при живой БД одно поведение, без неё другое."""
    import genome_intake as gi
    import health_db
    monkeypatch.setenv("ALLOW_WRITE_NONPRIMARY", "1")
    health_db.init_db()                  # сид пишет миграция init_db, фикстура её не зовёт
    with health_db.get_conn() as c:
        seeded = {r[0]: r[1] for r in c.execute(
            "SELECT key, value_num FROM system_config WHERE key LIKE 'genome.chip_%'")}
    assert seeded == gi._CHIP_FALLBACK
    assert gi.chip_identity_limits() == (0.005, 1000)
